source-file ~/.config/tmux/tmux.tokyonight_moon.conf
set -g prefix ^A
set -g mouse on

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g base-index 1

set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 1000000
set -g renumber-windows on

# required for image.nvim  
set -gq allow-passthrough on
set -g visual-activity off


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# vim-tmux-navigator plugin config
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
